################## localhost requests ##################

GET http://localhost:8765 HTTP/1.1
content-type: application/json

###

POST http://localhost:8765/password-reset-request HTTP/1.1
content-type: application/json

{
  "email": "craigroe7@gmail.com",
  "host": "https://staging.matchmemd.com"
}

###
POST http://localhost:8765/verify-email-request HTTP/1.1
content-type: application/json

{
  "email": "craigroe7@gmail.com",
  "first_name": "Craig",
  "host": "https://staging.matchmemd.com"
}

###
PUT http://localhost:8765/contact-request HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJjOGUyYjI5NmM2ZjMyODRlYzMwYjg4NjVkNzI5M2U2MjdmYTJiOGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbWF0Y2htZW1kLXN0YWdpbmctMzA4OTA3IiwiYXVkIjoibWF0Y2htZW1kLXN0YWdpbmctMzA4OTA3IiwiYXV0aF90aW1lIjoxNjE5MDQwODI0LCJ1c2VyX2lkIjoidWJxOUdRZzZnblp5SE9oRllza1BBVVlPNzNBMiIsInN1YiI6InVicTlHUWc2Z25aeUhPaEZZc2tQQVVZTzczQTIiLCJpYXQiOjE2MTkwNDA4MjQsImV4cCI6MTYxOTA0NDQyNCwiZW1haWwiOiJjcmFpZ3JvZTdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNyYWlncm9lN0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Zs3G4gspI0Pb-f9kpfhLqoNrjNFhpsNgVHtyvLhC9IV-xMiecRVWfcblYey9z85gSBDWWW3YysFNWRslwFPapf9WMg49n7l7bofOW5QMhDnMb69WEOdd2Cy862Tk8_JqPu2TehHJVz9erZjWaIqQDZrWmCQ1NQ0Y7IuhUYkAv9OAMcW13UJV_l6hzMXowkNkX0YZ5f6uu2196tNEBlKJU4INyOJjIv6QhOPDeHqTcRV2_LEkO8zLbjjy5ZAPbjoWLcDhKpFX5ZGmMNv0X9qjVCyFfGwSkVrq2nGXUo5vfq2ggqcZSD_mOTHFDtNzGVyqHsl2Ziyn3i81kIAYNegi5Q

# Gender              string `json:"e13_T"`
# DateOfBirth         int    `json:"e14_N"`
# MedicalStatus       string `json:"e15_T"`
# Specialties         string `json:"e9_T"`
# HasClinicalInterest string `json:"e16_T"`
# Clinicals           string `json:"e10_T"`
# VisaRequired        string `json:"e12_T"`
# School              string `json:"e5_T"`
# StartDate           string `json:"e11_T"`
{
  "email": "test123@gmail.com",
  "first_name": "Craig",
  "last_name": "Edwards",
  "country": "Dominica",
  "custom_fields": {
    "e10_T": "core, tesfggt",
    "e16_T": "true",
    "e14_N": 123532545,
    "e12_T": "true",
    "e5_T": "university ofsdfsf whatever",
    "e13_T": "male",
    "e9_T": "med, mdfsdfsreri, test",
    "e15_T": "graduate",
    "e11_T": "medium"
  }
}

################## Staging requests ##################

###
PUT https://us-east1-matchmemd-staging-308907.cloudfunctions.net/contact-request HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJjOGUyYjI5NmM2ZjMyODRlYzMwYjg4NjVkNzI5M2U2MjdmYTJiOGYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbWF0Y2htZW1kLXN0YWdpbmctMzA4OTA3IiwiYXVkIjoibWF0Y2htZW1kLXN0YWdpbmctMzA4OTA3IiwiYXV0aF90aW1lIjoxNjE5MDQwODI0LCJ1c2VyX2lkIjoidWJxOUdRZzZnblp5SE9oRllza1BBVVlPNzNBMiIsInN1YiI6InVicTlHUWc2Z25aeUhPaEZZc2tQQVVZTzczQTIiLCJpYXQiOjE2MTkwNDA4MjQsImV4cCI6MTYxOTA0NDQyNCwiZW1haWwiOiJjcmFpZ3JvZTdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbImNyYWlncm9lN0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Zs3G4gspI0Pb-f9kpfhLqoNrjNFhpsNgVHtyvLhC9IV-xMiecRVWfcblYey9z85gSBDWWW3YysFNWRslwFPapf9WMg49n7l7bofOW5QMhDnMb69WEOdd2Cy862Tk8_JqPu2TehHJVz9erZjWaIqQDZrWmCQ1NQ0Y7IuhUYkAv9OAMcW13UJV_l6hzMXowkNkX0YZ5f6uu2196tNEBlKJU4INyOJjIv6QhOPDeHqTcRV2_LEkO8zLbjjy5ZAPbjoWLcDhKpFX5ZGmMNv0X9qjVCyFfGwSkVrq2nGXUo5vfq2ggqcZSD_mOTHFDtNzGVyqHsl2Ziyn3i81kIAYNegi5Q

# Gender              string `json:"e13_T"`
# DateOfBirth         int    `json:"e14_N"`
# MedicalStatus       string `json:"e15_T"`
# Specialties         string `json:"e9_T"`
# HasClinicalInterest string `json:"e16_T"`
# Clinicals           string `json:"e10_T"`
# VisaRequired        string `json:"e12_T"`
# School              string `json:"e5_T"`
# StartDate           string `json:"e11_T"`
{
  "email": "test123@gmail.com",
  "first_name": "Craig",
  "last_name": "Edwards",
  "country": "Dominica",
  "custom_fields": {
    "e10_T": "core, tesfggt",
    "e16_T": "true",
    "e14_N": 123532545,
    "e12_T": "true",
    "e5_T": "university ofsdfsf whatever",
    "e13_T": "male",
    "e9_T": "med, mdfsdfsreri, test",
    "e15_T": "graduate",
    "e11_T": "medium"
  }
}

###
POST https://us-east1-matchmemd-staging-308907.cloudfunctions.net/password-reset-request HTTP/1.1
content-type: application/json

{
  "email": "craigroe7@gmail.com",
  "host": "https://staging.matchmemd.com"
}