GET http://localhost:8765 HTTP/1.1
content-type: application/json

###

POST http://localhost:8765/password-reset-request HTTP/1.1
content-type: application/json

{
  "email": "edwards.r.craig@gmail.com",
  "host": "https://staging.matchmemd.com"
}


###
POST https://us-east1-matchmemd-staging-308907.cloudfunctions.net/password-reset-request HTTP/1.1
content-type: application/json

{
  "email": "edwards.r.craig@gmail.com",
  "host": "https://staging.matchmemd.com"
}